### ISSUE TITLE
Problems with knognac on generated graphs

### ISSUE THREAD

**Issue by louisjac** [karmaresearch/kognac#1]
Hi,

First, I would like to thank you for making your work publicly available. 

I am currently trying to load the [following generated graph](https://github.com/karmaresearch/kognac/files/2138049/graph.txt) into Vlog and the whole process crashes with a "Floating point exception". 

I think I have pinpointed to problem to kognac file kognac/src/kognac/compression/compressor.cpp at the line 1943: the size of partitions is computed as sampleSize/ #partitions but there are 8 partitions and the sample contains 5 elements as shown in the [following debug](https://github.com/karmaresearch/kognac/files/2138052/debug.txt), which means sizePartition is 0 and the "% sizePartition" of line 1948 is bound to crash.  I have no idea what the correct fix should be but including a "if(sizePartition)" before the loop prevents the crash (but the data is not loaded).

Thanks in advance!

**Comment by CerielJacobs** [comment]
Fixed
